unbind C-b
unbind C-a
set -g prefix C-f
set -g prefix2 C-j
bind C-f send-prefix
bind C-j send-prefix -2

unbind |
unbind -
bind v split-window -h
bind h split-window -v
unbind %
unbind '"'

set -g mouse on

set -g base-index 1
setw -g pane-base-index 1

bind r source-file ~/.tmux.conf \; display-message "Config reloaded"

set -g history-limit 10000
set -sg escape-time 10
set -g renumber-windows on

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

bind -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel "wl-copy"
bind -T copy-mode MouseDragEnd1Pane send -X copy-pipe-and-cancel "wl-copy"

set -g status-right "#[fg=red,bold]Prefix: C-f/C-j#[default] | %H:%M "
